# A pod with no securityContext specified.
# Without the webhook, it would run as user root (0). The webhook mutates it
# to run as the non-root user with uid 1234.
apiVersion: v1
kind: Pod
metadata:
  name: pod-working
  labels:
    app: pod-working
spec:
  restartPolicy: OnFailure
  containers:
    - name: local-busybox
      image: localhost:5000/busybox
